### ISSUE TITLE
Show existing to-do tasks

### ISSUE THREAD

**Issue by amohapatra123** [the-browser-toolbox/to-do#18]
@adityabisoi the last issue #16 is completed and I have made the PR #17 so can i start working on this.

**Comment by adityabisoi** [comment]
@amohapatra123 The convention is to, provide a short title, and describe your proposal in the description.

**Comment by amohapatra123** [comment]
In the PR #17 we were just adding the to-do to the chrome storage but when the next time the extension is opened it it not present as we are not fetching it form the storage again,
so in this issue we will be fetching the to-do when the extension is opened.
