### ISSUE TITLE
Add issue template: feature request

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/to-do#2]
Add an issue template for requesting new features in the project.

**Comment by ak7550** [comment]
Hey @adityabisoi , I would like to work on the issue. Please assign this to me.

**Comment by adityabisoi** [comment]
@ak7550 Complete assigned ones first.

**Comment by nidz27** [comment]
@adityabisoi I would like to work on the issue. Please assign this to me. Where can I discuss the details about it with you?

**Comment by adityabisoi** [comment]
@nidz27 In the Gitter channel.
