### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [the-browser-toolbox/to-do#23]

**Comment by adityabisoi** [comment]
Please give a proper description

**Comment by maximilianschmelzer** [comment]
Sure, sorry. Currently it is not possible to change the order of the tasks (only if you delete and re add all of them). So I think it would be awesome to just drag tasks up and down to change the current position. This should be possible with draggable and a bit of js.

 I hope this explains it well enough. If not I can add an example if you want.
