### ISSUE TITLE
Add to-do on selection

### ISSUE THREAD

**Issue by amohapatra123** [the-browser-toolbox/to-do#26]
We can have a feature like the user can directly select some text from the browser and add it to the list.

**Comment by amohapatra123** [comment]
@adityabisoi can we have a feature like this??

**Comment by adityabisoi** [comment]
@amohapatra123 I think this is a good idea, but does not have a practical everyday application. Can you give an example of what you have thought of, maybe?

**Comment by amohapatra123** [comment]
Like let's say the user is doing something on the  browser and see some text which is relevant to the task he need's to do ,
so he can simply select that text and add to the list without opening the extension.

**Comment by adityabisoi** [comment]
I think, selecting a short text like `do assignments` or `study` can be entered manually, and selecting these short texts from a page is not really practical.

**Comment by amohapatra123** [comment]
ok
