### ISSUE TITLE
Responsive Navbar 

### ISSUE THREAD

**Issue by 777ahesh** [the-browser-toolbox/to-do#35]
Can @adityabisoi or @subhangi2731 assign this issue to me...
I have Created this  type of UI for the Navbar

![to do list 1](https://user-images.githubusercontent.com/91421427/144971780-3545b4b4-9a43-4f03-a89e-13b55c94a961.png)
![To-do List Windows](https://user-images.githubusercontent.com/91421427/144971790-ecc21528-8cde-4e5d-82fc-7c1d9261630a.png)

**Comment by adityabisoi** [comment]
Sure,go ahead. Be sure to setup the project as shown in README, and the changes should be reflected in the extension's popup.
