### ISSUE TITLE
Fix extension UI

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/to-do#36]
Currently, the UI is broken and looks like this
![Screenshot from 2021-12-07 11-08-27](https://user-images.githubusercontent.com/42573842/144972851-ca508c27-65c5-4273-a69e-a86cb20b3541.png)

Fix the UI

**Comment by 777ahesh** [comment]
@adityabisoi  can is work on this

**Comment by adityabisoi** [comment]
@777ahesh Sure!

**Comment by 777ahesh** [comment]
@adityabisoi  I have made PR for it You can check it and merge it
