### ISSUE TITLE
Fix added item disappearing

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/to-do#39]
The items in the list are not visible after addition. Please fix this.
![Screenshot from 2021-12-08 09-08-18](https://user-images.githubusercontent.com/42573842/145144371-dd2bc65c-5cc1-4033-89de-d5e6759e2f64.png)

**Comment by lokesh-0706** [comment]
Can you please assign me this issue?

**Comment by siddiq-1018** [comment]
@adityabisoi Can you please assign me this issue?

**Comment by adityabisoi** [comment]
@lokesh-0706 Go ahead, since you commented first

**Comment by vaibhavaaditya** [comment]
can i work on this issue?

**Comment by adityabisoi** [comment]
@vaibhavaaditya Sure!
