### ISSUE TITLE
Modified homepage 

### ISSUE THREAD

**Issue by mandiraghosh783** [the-browser-toolbox/to-do#40]
Here I have added a few quotes to make the user stay motivated and finish his/her work without procrastinating.

**Comment by adityabisoi** [comment]
@mandiraghosh783 Nice idea. However, in open source, you should always open an issue first, and start working after receiving reviews from the maintainers.

**Comment by mandiraghosh783** [comment]
Ok . Will keep that in mind 🙂

**Comment by mandiraghosh783** [comment]
@adityabisoi , I have already made a pr this time. Can you please look into it once?
