### ISSUE TITLE
Add gulpfile

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/to-do#5]
`gulp.js` is a workflow automation tool for JavaScript. Write a `gulpfile` for the project with the following operations: `watch`,  `build`, and `default` for running both simultaneously.

**Comment by rahulgogia65** [comment]
I am interested on working on this. I will be able to create tasks for all the three but can you let me know which files to watch in the watch task and what to do in the build task. Can you assign me this?

**Comment by adityabisoi** [comment]
Place the files inside a `src/` folder and watch it.
