### ISSUE TITLE
Add popup page and background script

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/to-do#6]
Add a simple popup page showing `Hello World` and a background script to the extension. These will be the initial setup files, the popup page is for UI, and the background script is for handling the business logic of the extension.

**Resources:** https://github.com/the-browser-toolbox/docs/actions/new

**Comment by amohapatra123** [comment]
can I work on this issue @adityabisoi ,I have made a PR for adding the manifest file

**Comment by adityabisoi** [comment]
@amohapatra123 Go ahead

**Comment by amohapatra123** [comment]
@adityabisoi can you please tell what will the background script contain, like as a to-do app it would be running only when the user has opened the extension.

**Comment by adityabisoi** [comment]
@amohapatra123 Yes, add a simple popup with Hello World and background script with Hello World as well. It should later be extended to be able to manage and add short to-do tasks.
