### ISSUE TITLE
Add linting and formatting

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/to-do#8]
For consistency in styling, linters, and code formatters are used. The most popular ones for JavaScript are `ESLint` and `Prettier`.
Add linting and formatting support to the project.

**Tip:** Use the configuration files and scripts at https://gitlab.com/adityabisoi/aossie-scholar

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 Please go ahead ;)

**Comment by ghost** [comment]
Can you assign this to me? We get bad commits because everyones ide changes the format differently, so its a bit more urging.

**Comment by adityabisoi** [comment]
Unassigned @subhangi2731   due to inactivity. Assigning @maximilianschmelzer

**Comment by ghost** [comment]
See https://github.com/the-browser-toolbox/to-do/pull/27. I kept the default style agreements as is, so I recommend everyone who wants a change in it, to create a pull request, where everyone can vote 🙂

I also added husky so the code is checked automatically, to prevent unlinted code in `main`. Maybe we should add a GitHub action too?

**Comment by adityabisoi** [comment]
Not Actions for now, I will see if I get the time to deploy it on Travis CI
